import Image from "next/image";
import MagnetosphereImage from "../../../../../public/magnetosphere.jpeg";

export default function Page() {
  return (
    <main className="flex flex-col gap-4">
      <h1 className="text-4xl mb-3">Magnetosphere</h1>
      <p>
        A magnetosphere is the region around a planet dominated by the
        planet&apos;s magnetic field. Other planets in our solar system have
        magnetospheres, but Earth has the strongest one of all the rocky
        planets: Earth&apos;s magnetosphere is a vast, comet-shaped bubble,
        which has played a crucial role in our planet&apos;s habitability. Life
        on Earth initially developed and continues to be sustained under the
        protection of this magnetic environment. The magnetosphere shields our
        home planet from solar and cosmic particle radiation, as well as erosion
        of the atmosphere by the solar wind - the constant flow of charged
        particles streaming off the sun.
      </p>
      <p>
        Earth&apos;s magnetosphere is part of a dynamic, interconnected system
        that responds to solar, planetary, and interstellar conditions. It is
        generated by the convective motion of charged, molten iron, far below
        the surface in Earth&apos;s outer core. Constant bombardment by the
        solar wind compresses the sun-facing side of our magnetic field. The
        sun-facing side, or dayside, extends a distance of about six to 10 times
        the radius of the Earth. The side of the magnetosphere facing away from
        the sun - the nightside - stretches out into an immense magnetotail,
        which fluctuates in length and can measure hundreds of Earth radii, far
        past the moon&apos;s orbit at 60 Earth radii.
      </p>
      <p>
        NASA heliophysics studies the magnetosphere to better understand its
        role in our space environment. Such research helps unravel the
        fundamental physics of space, which is dominated by complex
        electromagnetic interactions unlike what we experience day-to-day on
        Earth. By studying this space environment close to home, we can better
        understand the nature of space throughout the universe. Additionally,
        space weather within the magnetosphere - where many of our spacecraft
        reside - can sometimes have adverse effects on space technology as well
        as communications systems. Better understanding of the science of the
        magnetosphere helps improve our space weather models.
      </p>
      <p>
        NASA&apos;s studies of the magnetosphere include research into:
        understanding the nature of the electromagnetic phenomena in near-Earth
        space; how near-Earth space responds to external and internal stimuli;
        how the coupled middle and upper atmosphere respond to external factors;
        and how the various regions of the magnetosphere and upper atmosphere
        interact with each other.
      </p>
      <p>
        NASA heliophysics missions contributing to magnetospheric research are:
        Balloon Array for Radiation-belt Relativistic Electron Losses; Geotail;
        the Magnetospheric Multiscale mission, Time History of Events and
        Macroscale Interactions during Substorms; Two Wide-Angle Imaging
        Neutral-Atom Spectrometers; and the Van Allen Probes. Additionally,
        instruments on other NASA missions -- for example, Juno, which observes
        Jupiter -- observe the magnetosphere of other planets.
      </p>
      <Image
        src={MagnetosphereImage}
        alt="Magnetosphere"
        width={700}
        height={700}
      />
    </main>
  );
}
