export default function Page() {
  return (
    <main className="flex flex-col gap-4">
      <h1 className="text-4xl mb-3">Sun Magnetic Field</h1>
      <p>Here&apos;s a simplified explanation of how this process works:</p>
      <ul className="flex flex-col gap-2">
        <li>
          1. Convection in the Sun&apos;s Interior: The Sun is composed mostly
          of hydrogen and helium in a state of extremely hot, ionized gas known
          as plasma. In the Sun&apos;s core, where temperatures and pressures
          are incredibly high, nuclear fusion reactions convert hydrogen into
          helium, releasing a tremendous amount of energy. This energy moves
          outward through the Sun&apos;s layers by radiation and, more
          importantly, through a process called convection.
        </li>
        <li>
          2. Differential Rotation: The Sun does not rotate uniformly. Different
          parts of the Sun rotate at different rates. The equator rotates faster
          than the poles. This differential rotation causes the twisting and
          shearing of the magnetic field lines within the Sun.
        </li>
        <li>
          3. Magnetic Field Generation: The movement of charged particles in the
          Sun&apos;s interior generates electric currents. These electric
          currents, combined with the differential rotation, create a dynamo
          effect. This effect amplifies and sustains the magnetic field within
          the Sun.
        </li>
        <li>
          4. Emergence of Magnetic Field: The magnetic field generated in the
          Sun&apos;s interior eventually becomes buoyant due to the pressure and
          temperature conditions in various layers of the Sun. Magnetic field
          lines (buoy up) and rise towards the surface, a process known as
          magnetic flux emergence.
        </li>
        <li>
          5. Sunspots and Solar Activity: When magnetic field lines emerge at
          the Sun&apos;s surface, they can manifest as dark regions known as
          sunspots. Sunspots are areas of concentrated magnetic activity on the
          Sun&apos;s surface and are often associated with solar flares, coronal
          mass ejections (CMEs), and other solar phenomena.
        </li>
      </ul>
      <p>
        The Sun&apos;s magnetic field is not static but undergoes an
        approximately 11-year cycle called the solar cycle. During this cycle,
        the Sun&apos;s magnetic field strength and polarity reverse, reaching a
        maximum (solar maximum) and minimum (solar minimum) over this period.
        This cycle is driven by the complex interactions and dynamics of the
        solar dynamo.
      </p>
      <p>
        In summary, the Sun&apos;s magnetic field is generated by the motion of
        charged particles in its interior, driven by nuclear fusion and
        convection. The differential rotation and buoyant rise of magnetic field
        lines create the Sun&apos;s complex and dynamic magnetic field, which
        influences solar activity and phenomena.
      </p>
    </main>
  );
}
