export default function Page() {
  return (
    <main className="flex flex-col gap-4">
      <h1 className="text-4xl mb-3 font-bold">Magnetic Field Lines</h1>
      <p>
        Magnetic field lines are an abstract representation of the invisible
        forces generated by magnetic fields. They offer a visual depiction of
        the pathways and direction of these forces in the space surrounding a
        magnetic source, like a magnet or a celestial body with a magnetic
        field.
      </p>
      <p>
        These lines, as governed by the principles of electromagnetism, form
        continuous loops, revealing the way magnetic energy flows. The density
        and curvature of these lines indicate the strength and orientation of
        the magnetic field at any given point.
      </p>
    </main>
  );
}
